sudo: required

services:
  - docker

before_script:
  - rm t/34-sqlite.t
  - rm plugins/MultiBlog/t/02.tags.t
  - rm t/dangling-symlinks.t

script:
  - docker run -t -v $PWD:/mt -w /mt masiuchi/docker-mt-test:trusty-full bash -c "cpm install -g --test --cpanfile=t/cpanfile && find /var/lib/mysql -type f | xargs touch && service mysql start && service memcached start && PERL_JSON_BACKEND=0 prove t plugins/*/t"

notifications:
  slack:
    secure: c11SdzxeFF23AlZS7b8jeCL8CJSn2Ire6ovAneFwHUUxb9jeG9lqC78mOJiE0Yrcdkv7beom4WVYrFY7ZoT+tD5RXNUkh8PcxPPXBFjvfDi5PCXwbNs1wb4Pa4bHAZvABgjCN8+21KQ6GcvlHl6sDQmhy/8v4yeYngOavsYfhMs=
